[package]
name = "my-project-webview"
version = "0.1.0"
authors = ["Martyn Janes <martyn@obany.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "0.5.4", features = ["edge"] }